import type { Role } from "@prisma/client";

/**
 * System-wide granular permission identifiers.
 */
export const PERMISSIONS = {
  // Student permissions
  VIEW_OWN_PROFILE: "VIEW_OWN_PROFILE",
  VIEW_OWN_PERFORMANCE: "VIEW_OWN_PERFORMANCE",
  TAKE_ASSESSMENT: "TAKE_ASSESSMENT",
  TAKE_MOCK_TEST: "TAKE_MOCK_TEST",
  VIEW_OWN_ROADMAP: "VIEW_OWN_ROADMAP",
  VIEW_OWN_RECOMMENDATIONS: "VIEW_OWN_RECOMMENDATIONS",

  // Faculty permissions
  VIEW_ASSIGNED_STUDENTS: "VIEW_ASSIGNED_STUDENTS",
  VIEW_STUDENT_PERFORMANCE: "VIEW_STUDENT_PERFORMANCE",
  VIEW_ASSESSMENTS: "VIEW_ASSESSMENTS",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  ADD_STUDENT_NOTE: "ADD_STUDENT_NOTE",
  SEND_STUDENT_REMINDER: "SEND_STUDENT_REMINDER",

  // Management permissions
  MANAGE_STUDENTS: "MANAGE_STUDENTS",
  MANAGE_FACULTY: "MANAGE_FACULTY",
  MANAGE_ASSESSMENTS: "MANAGE_ASSESSMENTS",
  MANAGE_MOCK_TESTS: "MANAGE_MOCK_TESTS",
  MANAGE_ROADMAPS: "MANAGE_ROADMAPS",
  VIEW_REPORTS: "VIEW_REPORTS",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;

/**
 * Standard default permissions mapped to roles.
 */
export const ROLE_DEFAULT_PERMISSIONS: Record<Role, string[]> = {
  STUDENT: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.VIEW_OWN_PERFORMANCE,
    PERMISSIONS.TAKE_ASSESSMENT,
    PERMISSIONS.TAKE_MOCK_TEST,
    PERMISSIONS.VIEW_OWN_ROADMAP,
    PERMISSIONS.VIEW_OWN_RECOMMENDATIONS,
  ],
  FACULTY: [
    PERMISSIONS.VIEW_ASSIGNED_STUDENTS,
    PERMISSIONS.VIEW_STUDENT_PERFORMANCE,
    PERMISSIONS.VIEW_ASSESSMENTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.ADD_STUDENT_NOTE,
    PERMISSIONS.SEND_STUDENT_REMINDER,
  ],
  MANAGEMENT: [
    // Management has all management permissions plus visibility across the portal
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MANAGE_FACULTY,
    PERMISSIONS.MANAGE_ASSESSMENTS,
    PERMISSIONS.MANAGE_MOCK_TESTS,
    PERMISSIONS.MANAGE_ROADMAPS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_PERMISSIONS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_ASSIGNED_STUDENTS,
    PERMISSIONS.VIEW_STUDENT_PERFORMANCE,
    PERMISSIONS.VIEW_ASSESSMENTS,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
};
